# Generated by Django 5.2.1 on 2025-06-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, verbose_name='класс')),
                ('number', models.IntegerField(blank=True, verbose_name='номер')),
                ('name', models.CharField(blank=True, max_length=240, verbose_name='название')),
                ('url', models.CharField(blank=True, max_length=240, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Лабораторная работа',
                'verbose_name_plural': 'Лабораторные работы',
            },
        ),
    ]
