# Generated by Django 5.2.1 on 2025-06-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='класс')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lab.grade', verbose_name='класс')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='номер')),
                ('name', models.CharField(max_length=240, verbose_name='название')),
                ('url', models.CharField(max_length=240, verbose_name='url')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='lab.grade', verbose_name='класс')),
            ],
            options={
                'verbose_name': 'Лабораторная работа',
                'verbose_name_plural': 'Лабораторные работы',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Сдано')),
                ('accepted', models.BooleanField(default=False, verbose_name='Подтверждение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='lab.student', verbose_name='Ученик')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='lab.work', verbose_name='Лабораторная работа')),
            ],
            options={
                'verbose_name': 'Отчет по лабораторной работе',
                'verbose_name_plural': 'Отчеты по лабораторной работе',
            },
        ),
    ]
