# Generated by Django 5.2.1 on 2025-06-03 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='автор')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Сдано')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='lab.work', verbose_name='Лабораторная работа')),
            ],
            options={
                'verbose_name': 'Отчет по лабораторной работе',
                'verbose_name_plural': 'Отчеты по лабораторной работе',
            },
        ),
    ]
