# Generated by Django 5.2.1 on 2025-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='label',
            field=models.CharField(default=1, max_length=5, verbose_name='Литер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.IntegerField(verbose_name='класс'),
        ),
    ]
