# Generated by Django 5.2.1 on 2025-06-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_student_label_alter_grade_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='литер')),
            ],
            options={
                'verbose_name': 'Литер',
                'verbose_name_plural': 'Литеры',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lab.litter', verbose_name='литер'),
        ),
    ]
