# Generated by Django 5.2.1 on 2025-06-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_litter_alter_student_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='label',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lab.litter', verbose_name='литер'),
        ),
    ]
