# Generated by Django 5.2.7 on 2025-10-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_student_label'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Litter',
            new_name='Letter',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
    ]
