# Generated by Django 5.2.7 on 2025-10-30 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'Раздел спавочника',
                'verbose_name_plural': 'Разделы справочника',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='приоритет')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('path_to_file', models.CharField(max_length=200, verbose_name='путь к файлу')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='guide.section', verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
